Repository ortizjavi/la-montaner, pull requests merged in 2021-08, with the labels that each got.

#1 install dependencies
  api/package-lock.json
  api/package.json
  client/package-lock.json
Labels: enhancement

#26 Details p
  client/package-lock.json
  client/package.json
  client/src/components/Loading/Loading.js
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/SearchBar/SearchBar.jsx
  client/src/constants.js
  client/src/index.css
  client/yarn.lock
Labels: enhancement

#32 Component sSeach
  client/package-lock.json
  client/src/actions/types.js
  client/src/components/SearchBar/SearchBar.css
  client/src/components/SearchBar/SearchBar.jsx
  client/src/components/SearchBar/UseGetProducts.jsx
  client/yarn.lock
Labels: enhancement

#31 refactor(client/src/containers): modify route names in App.jsx and refactored code
  api/index.js
  api/src/app.js
  api/src/models/GroupedProducts.js
  client/src/actions/types.js
  client/src/components/Home/Home.jsx
  client/src/components/SearchBar/SearchBar.jsx
  client/src/components/SearchBar/UseGetProducts.jsx
  client/src/constants.js
  client/src/containers/App.jsx
  client/src/index.jsx
  client/src/reducer/index.js
  client/src/reportWebVitals.js
Labels: refactor

#34 feat(client/src/components): add home buttons
  client/src/components/ProductCreation/ProductCreation.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/SearchBar/SearchBar.css
Labels: enhancement

#36 refactor(client/src/components/SearchBar): handleS
  client/src/components/SearchBar/SearchBar.jsx
Labels: refactor

#48 feat/refactor(client/src/actions): names, product
  client/src/actions/names.js
  client/src/actions/types/categoryActions.js
  client/src/actions/types/productActions.js
Labels: enhancement, refactor

#53 refactor(client/src/components): moved Sidebar.jsx code to Filters.jsx
  client/src/components/Filters/Filters.css
  client/src/components/Filters/Fiters.jsx
  client/src/components/Home/Home.jsx
  client/src/components/Sidebar/Sidebar.jsx
Labels: fix, refactor, delete

#62 fix(client/src/components): links
  client/src/components/Footer/Footer.jsx
  client/src/components/Landing/Landing.jsx
Labels: fix

#69 feat(client/src/components/ProductDetail):fix detail category
  client/src/components/ProductDetail/ProductDetail.css
  client/src/components/ProductDetail/ProductDetail.jsx
Labels: fix

#72 feat(client/src/components/Product): fix categories in component Prod…
  client/src/components/ProductDetail/ProductDetail.jsx
Labels: fix

#74 fix(api/src/controllers/General/searchProducts.js): category count in query
  api/src/controllers/General/searchProducts.js
Labels: fix

#75 feat(/api/src/controllers/General/searchProducts.js): fix filterProdu…
  api/src/controllers/General/searchProducts.js
Labels: fix

#77 feat(client/src/compoents/ShowProducts): add price
  client/src/components/ShowProducts/ShowProducts.css
  client/src/components/ShowProducts/ShowProducts.jsx
Labels: enhancement

#80 feat(client/src): cart actions and reducer
  client/src/actions/names.js
  client/src/actions/types/productActions.js
  client/src/reducer/index.js
Labels: enhancement

#85 feat/refactor(client/src): shopping cart actions and reducer & modify imports
  client/src/actions/names.js
  client/src/actions/types/categoryActions.js
  client/src/actions/types/productActions.js
  client/src/components/Navbar/NavBar.jsx
  client/src/reducer/index.js
  client/src/utils/endpoints.js
Labels: enhancement, fix, refactor, delete

#86 fix(client/src/store): add localStorage to redux store
  client/package.json
  client/src/store/index.js
Labels: fix

#87 feat(src/client/components/Cart): fix cart, add functions and actions)
  client/src/actions/types/productActions.js
  client/src/components/Cart/Cart.css
  client/src/components/Cart/Cart.jsx
  client/src/components/Cart/CartItem.css
  client/src/components/Cart/CartItem.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/containers/App.jsx
  client/src/store/index.js
Labels: enhancement, fix

#89 feat(src/client/components) add cart action, fix bugs
  client/src/components/Cart/Cart.jsx
  client/src/components/CategoryCreation/CategoryCreation.jsx
  client/src/components/DashboardAdmin/Dashboard.jsx
  client/src/components/EditProduct/EditProduct.jsx
  client/src/components/Home/Home.jsx
  client/src/components/Navbar/NavBar.jsx
  client/src/components/ProductCreation/ProductCreation.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/SearchBar/SearchBar.jsx
  client/src/reducer/cartReducers.js
  client/src/reducer/index.js
  client/src/store/index.js
Labels: enhancement, fix

#90 Cart
  client/src/actions/names.js
  client/src/actions/types/productActions.js
  client/src/components/Cart/Cart.jsx
  client/src/components/Cart/CartItem.jsx
  client/src/reducer/cartReducers.js
Labels: enhancement, fix

#91 feat/fix(client/src/components): style, link and stock
  client/src/components/Cart/Cart.css
  client/src/components/Cart/Cart.jsx
  client/src/components/Cart/CartItem.jsx
  client/src/components/Navbar/NavBar.jsx
Labels: enhancement, fix

#93 feat/refactor/fix/delete(client/src): new redux folder and fixed imports
  client/src/components/AdminPage/AdminPage.jsx
  client/src/components/Cart/Cart.jsx
  client/src/components/CategoryCreation/CategoryCreation.jsx
  client/src/components/DashboardAdmin/Dashboard.jsx
  client/src/components/EditProduct/EditProduct.jsx
  client/src/components/Home/Home.jsx
  client/src/components/Navbar/NavBar.jsx
  client/src/components/Order/Order.jsx
  client/src/components/Pagination/Pagination.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/SearchBar/SearchBar.jsx
  client/src/index.jsx
  client/src/reducer/index.js
  client/src/redux/actions/names.js
  client/src/redux/actions/types/categoryActions.js
  client/src/redux/actions/types/productActions.js
  client/src/redux/reducer/cartReducers.js
  client/src/redux/reducer/index.js
  client/src/redux/store.js
Labels: enhancement, fix, refactor, delete

#94 fix(src/redux/index): fix reducer
  client/src/redux/reducer/index.js
Labels: fix

#97 ProductDetail new carousel and css styles
  client/src/components/ProductDetail/ProductDetail.css
  client/src/components/ProductDetail/ProductDetail.jsx
Labels: enhancement, fix

#105 feat(client/src): wishlist
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/redux/actions/names.js
  client/src/redux/actions/types/productActions.js
  client/src/redux/reducer/wishlistReducer.js
  client/src/redux/store.js
  client/src/utils/localStorage.js
Labels: enhancement

#106 feat(client/src/): wishlist component & style
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/Wishlist/Wishlist.css
  client/src/components/Wishlist/Wishlist.jsx
  client/src/containers/App.jsx
  client/src/redux/actions/types/productActions.js
  client/src/redux/reducer/wishlistReducer.js
  client/src/redux/store.js
Labels: enhancement, refactor, delete

#107 fix(src/client/components/ProductDetail):fix button heart functionality
  client/src/components/ProductDetail/ProductDetail.css
  client/src/components/ProductDetail/ProductDetail.jsx
Labels: fix

#111 feat(client/src/): back home button & fix(client/src): wishlist route
  client/src/components/Wishlist/Wishlist.css
  client/src/components/Wishlist/Wishlist.jsx
  client/src/containers/App.jsx
Labels: enhancement, fix

#112 fix(client/src/componets): back to home button
  client/src/components/Cart/Cart.css
  client/src/components/Cart/Cart.jsx
Labels: fix

#118 fix(front/Home&App): css fix
  client/src/components/Home/Home.css
  client/src/containers/App.css
Labels: fix

#119 fix(client/src/components): image not showing
  client/src/components/Wishlist/Wishlist.jsx
Labels: fix

#120 fix(client/src/components): back home button and feat(client/src/compoents): delete button
  client/src/components/Wishlist/Wishlist.css
  client/src/components/Wishlist/Wishlist.jsx
Labels: enhancement, fix

#124 feat(client/src/components): initial responsive
  client/src/components/Wishlist/Wishlist.css
Labels: enhancement

#126 fix(src/client/components/Footer): fix styles in Footer and About page
  client/src/components/About/About.css
  client/src/components/About/About.jsx
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.jsx
  client/src/img/beerPinta.png
Labels: enhancement, fix

#127 feat(client/components/): registerForm & loginForm + feat(api/controllers/admin): reset password & reset user
  api/src/controllers/Admin/Admin/getUsers.js
  api/src/controllers/Admin/Admin/index.js
  api/src/controllers/Admin/Admin/resetUser.js
  api/src/controllers/Admin/Auth/externalLogin.js
  api/src/controllers/Admin/Auth/index.js
  api/src/controllers/Admin/Auth/register.js
  api/src/controllers/Admin/Auth/resetPassword.js
  api/src/middlewares/auth.js
  api/src/models/Users/User.js
  api/src/routes/adminRoutes.js
  api/src/routes/authRoutes.js
  api/src/utils/verifyJWT.js
  client/src/components/Authentication/Authentication.jsx
  client/src/components/CategoryCreation/CategoryCreation.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/ModalDialog/LoginForm.css
  client/src/components/ModalDialog/LoginForm.jsx
  client/src/components/ModalDialog/RegisterForm.jsx
  client/src/components/Navbar/NavBar.css
  client/src/components/Navbar/NavBar.jsx
  client/src/components/PrivateRoute/PrivateRoute.js
  client/src/components/PublicRoute/PublicRoute.jsx
  client/src/containers/App.jsx
  client/src/redux/actions/names.js
  client/src/redux/actions/types/authActions.js
  client/src/redux/reducer/sessionReducer.js
  client/src/utils/constans.js
  client/src/utils/constants.js
  client/src/utils/endpoints.js
Labels: enhancement, fix

#132 fix(src/client/components):change styles in home and about / faq pages
  client/src/components/About/About.css
  client/src/components/About/FAQ.css
  client/src/components/Footer/Footer.jsx
  client/src/components/Home/Home.jsx
  client/src/components/Navbar/NavBar.css
  client/src/components/Navbar/NavBar.jsx
  client/src/components/Pagination/Pagination.css
  client/src/components/SearchBar/SearchBar.css
  client/src/components/SearchBar/SearchBar.jsx
  client/src/img/logopng.png
Labels: fix

#131 LoginForm & RegisterForm
  api/src/controllers/Admin/Auth/register.js
  client/src/components/ModalDialog/LoginForm.css
  client/src/components/ModalDialog/LoginForm.jsx
  client/src/components/ModalDialog/RegisterForm.jsx
  client/src/redux/actions/names.js
  client/src/redux/actions/types/authActions.js
  client/src/redux/reducer/sessionReducer.js
Labels: enhancement, fix

#134 feat(client/src/components): rel noopener noreferrer
  client/src/components/About/About.jsx
  client/src/components/Footer/Footer.jsx
Labels: enhancement

#141 fix(client/src/components): no product text & responsive.
  client/src/components/Wishlist/Wishlist.css
  client/src/components/Wishlist/Wishlist.jsx
Labels: enhancement, fix

#144 feat(client/src/components): delete all cart
  client/src/components/Cart/Cart.css
  client/src/components/Cart/Cart.jsx
Labels: enhancement, fix

#145 fix(client/src/redux/authActions): login action
  client/src/components/Authentication/Authentication.jsx
  client/src/redux/actions/types/authActions.js
  client/src/redux/store.js
Labels: bug, fix

#150 feat(clien/src/components): cart subtotal in navbar and fix(client/src/components): grammar
  client/src/components/Cart/Cart.jsx
  client/src/components/Navbar/NavBar.css
  client/src/components/Navbar/NavBar.jsx
  client/src/redux/actions/names.js
  client/src/redux/actions/types/productActions.js
  client/src/redux/reducer/cartReducers.js
  client/src/redux/store.js
Labels: enhancement, fix

#149 feat(src/client/components/ProductDetail & NavBar): change wishlist p…
  client/src/components/Navbar/NavBar.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/ShowProducts/ShowProducts.jsx
Labels: enhancement, fix

#170 feat(client/src/components): add review to products after buy
  client/src/components/Cart/Cart.css
  client/src/components/Cart/CartItem.css
  client/src/components/Cart/CartItem.jsx
  client/src/components/Footer/Footer.css
  client/src/components/Footer/Footer.jsx
  client/src/components/Navbar/NavBar.css
  client/src/components/ProductDetail/ProductDetail.css
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/ProductDetail/Reviews.css
  client/src/components/ProductDetail/Reviews.js
  client/src/index.css
Labels: enhancement, fix

#172 refactor (client/src/components): imports in ProductDetail, Cart, and function in Reviews
  client/src/components/Cart/Cart.jsx
  client/src/components/Cart/CartItem.jsx
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/ProductDetail/Reviews.js
Labels: fix, refactor

#177 feat(client/src/components): address map
  client/package.json
  client/src/components/FindUs/FindUs.css
  client/src/components/FindUs/FindUs.jsx
  client/src/components/Footer/Footer.jsx
  client/src/containers/App.jsx
  client/src/utils/constants.js
Labels: enhancement

#181 feat(client/src/components): product info and review buttons
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/ProductDetail/Reviews.css
  client/src/components/ProductDetail/Reviews.js
Labels: enhancement

#186 fix(client/src/components): back button style
  client/src/components/Wishlist/Wishlist.css
  client/src/components/Wishlist/Wishlist.jsx
Labels: fix

#184 feat(client/src/components): upgrade buttons logic
  client/src/components/ProductDetail/Reviews.js
  client/src/redux/actions/types/productActions.js
Labels: enhancement, fix, delete

#185 feat(client/src/components): empty cart button logic
  client/src/components/Cart/Cart.css
  client/src/components/Cart/Cart.jsx
  client/src/redux/reducer/cartReducers.js
Labels: enhancement

#194 refactor(client/src/components): linter in components
  client/src/components/About/About.css
  client/src/components/About/About.jsx
  client/src/components/About/FAQ.css
  client/src/components/About/FAQ.jsx
  client/src/components/Cart/Cart.css
  client/src/components/Cart/Cart.jsx
  client/src/components/Cart/CartItem.css
  client/src/components/Cart/CartItem.jsx
  client/src/components/FindUs/FindUs.css
  client/src/components/FindUs/FindUs.jsx
  client/src/components/Landing/Landing.css
  client/src/components/Landing/Landing.jsx
  client/src/components/Loading/Loading.css
  client/src/components/Loading/Loading.js
  client/src/components/ProductDetail/ProductDetail.css
  client/src/components/ProductDetail/ProductDetail.jsx
  client/src/components/ProductDetail/Reviews.css
  client/src/components/ProductDetail/Reviews.js
  client/src/components/Wishlist/Wishlist.css
  client/src/components/Wishlist/Wishlist.jsx
Labels: refactor
